  name: CI
  on: [pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - run: |
            mkdir -p ~/.gradle
            echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
            restore-keys: |
             ${{ runner.os }}-gradle-
        - uses: eskatos/gradle-command-action@v1
          with:
            arguments: build
